config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :update]

  resources :topics

  post :incoming, to: 'incoming#create'

  get 'about' => 'welcome#about'
  root to: 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    #puts "INCOMING PARAMS HERE: #{params}"


    @user = User.find_by(email: params["Return-Path"])
    @topic = Topic.find_by(title: params[:subject])
    @url = params["body-plain"]     

    if @user.nil?
      user = User.new(
        name:     params["Return-Path"], 
        email:    params["Return-Path"],
        password: 'helloworld'
      )
      user.skip_confirmation!
      user.save!     
    end

    if @topic.nil?
      topic = Topic.new(
        title:    params[:subject],
        user:     user  
      )
      topic.save!
    end

    @bookmark = Bookmark.find_by(url: @url)
    if @bookmark.nil?
      bookmark = Bookmark.new(
        topic:    topic,
        url:      @url
      )
      bookmark.save!
    end


    head 200
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
    @topic.user = current_user
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to topics_path
    else
      flash[:error] = "Error saving topic, please try again."
      redirect_to topics_path 
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      flash[:notice] = "Topic was updated successfully."
      redirect_to topics_path
    else
      flash[:error] = "Topic was not updated. Please try again."
      redirect_to topics_path
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    title = @topic.title
    if @topic.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic. Please try again."
      render :show
    end
  end
  
  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_later
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information udpated"
      redirect_to current_user
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
            Blocmarks
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Topics", topics_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li>
                  <%= link_to current_user do %>
                    Hello <%= (current_user.name || current_user.email) %>!</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <span class="glyphicon glyphicon-user"></span>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="glyphicon glyphicon-log-out"></span>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to new_user_session_path do %>
                    <span class='glyphicon glyphicon-log-in'></span> Sign In
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path do %>
                    <span class='glyphicon glyphicon-user'></span> Sign Up
                  <% end %>
                </li>
              <% end %>
            </div>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/topics/_form.html.erb
<div class="row">
  <%= form_for @topic do |f| %>
    <div class="form-group">
      <div class="col-md-8"><%= f.text_field :title, class: 'form-control field-small', placeholder: "Enter topic" %></div>
      <span>
        <%= f.submit "Save", class: 'btn btn-success'%>
      </span>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8"><h3>Edit Topic</h3></div>
  </div>
  <%= render partial: 'form', locals: { topic: @topic } %>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <div><h1>All Topics</h1>
    <span><%= link_to new_topic_path(@topic), class: 'btn btn-success btn-xs' do %>
      <span class="has-tooltip" data-toggle="tooltip" title="New Topic">
        <span class="glyphicon glyphicon-plus">
        </span>
      </span>
    <% end %>
    </span>
    </div>
    <% @topics.each do |topic| %>
     <h3>
        <%= link_to topic, data: { confirm: 'Are you sure you want to delete this topic?' }, method: :delete, class: 'btn btn-danger btn-xs' do %>
          <span class="has-tooltip" data-toggle="tooltip" title="Delete Topic">
            <span class="glyphicon glyphicon-trash">
            </span>
          </span>
        <% end %>
        <%= link_to edit_topic_path(topic), class: 'btn btn-success btn-xs' do %>
          <span class="has-tooltip" data-toggle="tooltip" title="Edit Topic">
            <span class="glyphicon glyphicon-pencil">
            </span>
          </span>
        <% end %>
        <%= link_to "#{topic.title}", topic %>
      </h3>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8"><h3>New Topic</h3></div>
  </div>
  <%= render partial: 'form', locals: { topic: @topic } %>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <h3>Topic: <%= @topic.title %></h3>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if current_user.name %>
    <h3 class="media-heading"><%= current_user.name %></h3>
  <% end %>
  <p class="media-body"><%= current_user.email %></p>
</div>

app/views/welcome/about.html.erb
<div class="jumbotron">  
  <h3 class="media-heading">Social Bookmarking With Email Integration</h3>
  <small class="media-body">Created by: Noel Deguzman</small>
  <br>
  <p class="media-body">Build a production quality social bookmarking app that allows users to email, manage and share bookmarked URLs.</p>
</div>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <h1>Blocmarks</h1>
    <p>Blocmarks is a resource for sharing links with your friends!</p>
    <p>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    </p>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h2></h2>
      <p></p>
    </div>
    <div class="col-md-4">
      <h2></h2>
      <p></p>
    </div>
    <div class="col-md-4">
      <h2></h2>
      <p></p>
    </div>
  </div>